# Generated by Django 2.2.5 on 2019-12-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='remark',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
