# Generated by Django 2.2.5 on 2019-12-18 19:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_appinfo_remark'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appinfo',
            managers=[
                ('apps', django.db.models.manager.Manager()),
            ],
        ),
    ]
