# Generated by Django 2.2.5 on 2019-10-26 12:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hanme',
            new_name='hname',
        ),
    ]
